### ISSUE TITLE
Vidstab missing or removed

### ISSUE THREAD

**Issue by LVrooman54** [georgmartius/vid.stab#130]
Vidstab does not work with the latest download from Gyan's website. I checked the version listings
and it has not been included since version 6.11.

**Comment by thinrope** [comment]
Hi @LVrooman54 ! It is a good idea to report issues, I see you joined GitHub even seemingly to do that, but please add more information, if you'd like someone to be able to help you.
* What download (URL please) are you referring to?

May be it is an issue that you need to raise with the project on that site, since vidtab project hasn't done anything in the meantime.

**Comment by LVrooman54** [comment]
Hi thinrope,
I downloaded it from this specific location; https://www.gyan.dev/ffmpeg/builds/#release-builds
