### ISSUE TITLE
 Error while loading shared libraries

### ISSUE THREAD

**Issue by nicolazilio** [georgmartius/vid.stab#37]
Dear all, 

I followed this guide to compile ffmpeg. Before doing so I got the source code for the vid.stab library from GitHub and did

```
cmake -DCMAKE_INSTALL_PREFIX:PATH="/home/myusername/programs/ffmpeg/ffmpeg_build"
make
sudo make install
```

within the follwoing directory structure:

```
programs
    |_ ffmpeg
          |_ ffmpeg_build
                |_ lib
                      |_ pkgconfig
                |_ bin
                |_ include
                |_share
          |_ ffmpeg_sources
                |_ vid.stab
          |_ bin
```

At last, I compiled ffmpeg and exported `LD_LIBRARY_PATH`. However, when I run ffmpeg, I receive the following error message:

`./ffmpeg: error while loading shared libraries: libvidstab.so.1.1: cannot open shared object file: No such file or directory`

Does anybody have an idea of what could have gone wrong? I can see `libvidstab.so.1.1` in ffmpeg_build/lib.

Thanks a bunch.

Nicola

**Comment by georgmartius** [comment]
Hi,
did you also install the vid.stab library itself? 
It cannot be found at runtime. You can either install it in the system (with sudo make install)
or use LD_LIBRARY_PATH to point the linker to the path of the lib file.

Hope it helps.

**Comment by nicolazilio** [comment]
It looks like I need export LD_LIBRARY_PATH before running ffmpeg every time I start a new shell, I don't know if this is the expected behaviour, but it works this way.

**Comment by tlum** [comment]
It depends on your intentions. Mine was to create a static build of ffmpeg because there is often a lot of trouble getting RHEL and derivative distros to agree on shared library version requirements... so I just opt to build and statically link the requirement. But to do that you have to decipher the switch to generate static libraries. In this case I was able to use:

```
cd ~/ffmpeg_sources
git clone https://github.com/georgmartius/vid.stab.git
cd vid.stab
cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/ffmpeg_build -DBUILD_SHARED_LIBS:bool=off .
make
make install
```
So, if you're intending to link static libs, this error happens because vid.stab defaults to shared. If you're intending to use shared libs then that's another whole can of worms.
